-- ====================================================================
-- NTB LAB PORTAL - SUPABASE DATABASE SCHEMA MIGRATION
-- ====================================================================

-- 1. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. AUTOMATED TIMESTAMP TRIGGER FUNCTION
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
   NEW.updated_at = NOW();
   RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 3. PROFILES TABLE (Linked to Supabase Auth)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT NOT NULL,
  full_name TEXT,
  role TEXT DEFAULT 'Technical Manager',
  section TEXT DEFAULT 'Mechanical',
  active_tasks INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TRIGGER update_profiles_updated_at
BEFORE UPDATE ON public.profiles
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- 4. SAMPLES TABLE
CREATE TABLE IF NOT EXISTS public.samples (
  id TEXT PRIMARY KEY,
  product TEXT NOT NULL,
  applicant TEXT,
  sample_type TEXT,
  date_received DATE DEFAULT CURRENT_DATE,
  forwarded_on DATE,
  quantity TEXT DEFAULT '1.00',
  standard TEXT,
  required_tests TEXT,
  documents TEXT[] DEFAULT '{}',
  remarks TEXT,
  priority TEXT DEFAULT 'Medium',
  testing_section TEXT DEFAULT 'Mechanical',
  test_type TEXT DEFAULT 'All',
  assigned_engineer TEXT,
  test_request_id TEXT,
  allocation_date DATE,
  due_date DATE,
  test_results JSONB,
  test_date DATE,
  result_status TEXT DEFAULT 'Pending',
  verification_status TEXT DEFAULT 'Pending Verification',
  report_number TEXT,
  report_date DATE,
  reporting_manager TEXT,
  status TEXT DEFAULT 'New Sample Received',
  type TEXT DEFAULT 'New',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TRIGGER update_samples_updated_at
BEFORE UPDATE ON public.samples
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- 5. CLARIFICATIONS TABLE
CREATE TABLE IF NOT EXISTS public.clarifications (
  id TEXT PRIMARY KEY,
  sample_id TEXT REFERENCES public.samples(id) ON DELETE CASCADE,
  product_name TEXT,
  query TEXT NOT NULL,
  date_raised DATE DEFAULT CURRENT_DATE,
  status TEXT DEFAULT 'Open',
  sent_to TEXT DEFAULT 'Sample Cell',
  response TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TRIGGER update_clarifications_updated_at
BEFORE UPDATE ON public.clarifications
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- 6. MANUALS TABLE (User Manuals & SOPs)
CREATE TABLE IF NOT EXISTS public.manuals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  updated_by TEXT DEFAULT 'Admin',
  date DATE DEFAULT CURRENT_DATE,
  published BOOLEAN DEFAULT true,
  file_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. SERIES TABLE (Batch Test Requests)
CREATE TABLE IF NOT EXISTS public.series (
  id TEXT PRIMARY KEY,
  product TEXT NOT NULL,
  applicant TEXT,
  request_date DATE DEFAULT CURRENT_DATE,
  sample_count INT DEFAULT 0,
  completed_reports INT DEFAULT 0,
  pending_reports INT DEFAULT 0,
  status TEXT DEFAULT 'Pending Requests',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. AUDIT LOGS TABLE
CREATE TABLE IF NOT EXISTS public.audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  time TEXT DEFAULT TO_CHAR(NOW(), 'YYYY-MM-DD HH24:MI:SS'),
  text TEXT NOT NULL,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. AUTOMATED USER PROFILE CREATION TRIGGER
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name, role, section)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'full_name', split_part(NEW.email, '@', 1)),
    COALESCE(NEW.raw_user_meta_data->>'role', 'Technical Manager'),
    COALESCE(NEW.raw_user_meta_data->>'section', 'Mechanical')
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- 10. ROW LEVEL SECURITY (RLS) POLICIES
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.samples ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clarifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.manuals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.series ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

-- Allow public / anon read and write access for development & fallback compatibility
-- (Can be restricted to auth.role() = 'authenticated' in strict enterprise deployment)

CREATE POLICY "Public Profiles Select" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Public Profiles Insert" ON public.profiles FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Profiles Update" ON public.profiles FOR UPDATE USING (true);

CREATE POLICY "Public Samples Select" ON public.samples FOR SELECT USING (true);
CREATE POLICY "Public Samples Insert" ON public.samples FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Samples Update" ON public.samples FOR UPDATE USING (true);
CREATE POLICY "Public Samples Delete" ON public.samples FOR DELETE USING (true);

CREATE POLICY "Public Clarifications Select" ON public.clarifications FOR SELECT USING (true);
CREATE POLICY "Public Clarifications Insert" ON public.clarifications FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Clarifications Update" ON public.clarifications FOR UPDATE USING (true);
CREATE POLICY "Public Clarifications Delete" ON public.clarifications FOR DELETE USING (true);

CREATE POLICY "Public Manuals Select" ON public.manuals FOR SELECT USING (true);
CREATE POLICY "Public Manuals Insert" ON public.manuals FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Manuals Update" ON public.manuals FOR UPDATE USING (true);
CREATE POLICY "Public Manuals Delete" ON public.manuals FOR DELETE USING (true);

CREATE POLICY "Public Series Select" ON public.series FOR SELECT USING (true);
CREATE POLICY "Public Series Insert" ON public.series FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Series Update" ON public.series FOR UPDATE USING (true);

CREATE POLICY "Public Audit Logs Select" ON public.audit_logs FOR SELECT USING (true);
CREATE POLICY "Public Audit Logs Insert" ON public.audit_logs FOR INSERT WITH CHECK (true);

-- 11. INDEXES FOR PERFORMANCE
CREATE INDEX IF NOT EXISTS idx_samples_status ON public.samples(status);
CREATE INDEX IF NOT EXISTS idx_samples_testing_section ON public.samples(testing_section);
CREATE INDEX IF NOT EXISTS idx_clarifications_sample_id ON public.clarifications(sample_id);
